apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: harness-demo
  template:
    metadata:
      labels:
        app: harness-demo
    spec:
      containers:
      - name: hanrness-demo
        image: adzpppxbswbb/my-app:0dd15ce
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: harness-cd-service
spec:
  selector:
    app: harness-demo
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: harness-cd-service2
spec:
  selector:
    app: harness-demo
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
